GetCitiesAverageFruitsAndVegetablesPricesLowestCost
Flourless-IO/cost-of-living pull request #21
Opened 2023-02-17 17:32 UTC by youssefahmed55

Update GetCitiesAverageFruitsAndVegetablesPricesLowestCost

2023-02-17 20:39 UTC, Abdelrahman-Sedky requested changes
The Logic LGTM.
Some changes is required in testing.

2023-02-17 20:39 UTC, Abdelrahman-Sedky commented on src/test/kotlin/interactor/GetCitiesAverageFAVLowesCostTest.kt
> +    fun should_ReturnAtLeastTenCitiesNames_When_GetCitiesNamesThatAverageOfFruitsAndVegetablesHaveLowestCostAndAllCitiesHaveNotNullSalariesOrNullFruitsAndVegetablesPrices() {
**Please reconsider the following:**
1. The naming does not clarify the test case.
2. You can make the name short.
>  Ex: `should return at most ten cities names when given data with not null salaries and not null fruit and vegetable prices` 
3. use `` in naming for better readability.

2023-02-18 14:15 UTC, Abdelrahman-Sedky approved these changes
LGTM

2023-02-18 18:24 UTC, Abdelwahab-IO requested changes

2023-02-18 18:24 UTC, Abdelwahab-IO commented on src/main/kotlin/interactor/GetCitiesAverageFAVLowesCost.kt
>              .map { it.cityName }
use scope functions
handle negative limit case

2023-02-18 18:24 UTC, Abdelwahab-IO commented on src/test/kotlin/interactor/GetCitiesAverageFAVLowesCostTest.kt
add test case to handle limit with negative numbers

2023-02-21 05:04 UTC, Abdelwahab-IO approved these changes

2023-02-21 05:06 UTC, closed without merging