fix/get cities names and average salaries in country
Flourless-IO/cost-of-living pull request #22
Opened 2023-02-17 18:11 UTC by Abdallahx3x

exclude null salaries
make some changes to the tests

2023-02-17 21:37 UTC, Abdelrahman-Sedky requested changes
Great job so far.
some little changes are required.

2023-02-17 21:37 UTC, Abdelrahman-Sedky commented on src/main/kotlin/interactor/GetCitiesNamesAndAverageSalariesInCountry.kt
> +        if (list.isEmpty()) throw Exception("wrong name")
Use scope functions to do the same logic of this line and return the result value directly without the need of the variable `list`.

2023-02-17 21:37 UTC, Abdelrahman-Sedky commented on src/test/kotlin/interactor/GetCitiesNamesAndAverageSalariesInCountryTest.kt
> +    fun should_ThrowException_when_EnterEmptyName() {
Use `` **backticks** in naming for better readability.
> EX: `should throw exception when given empty name`

2023-02-17 21:37 UTC, Abdelrahman-Sedky commented on src/test/kotlin/interactor/GetCitiesNamesAndAverageSalariesInCountryTest.kt
> +        //when get the cities name and average salary in country
Better option
```suggestion
        //when get the cities name and average salary in country
        val ListOfCitiesAndSalaries = Executable { getResult.execute(country) }
        // then check the result
        assertThrows(Exception::class.java, ListOfCitiesAndSalaries)
```

2023-02-18 15:00 UTC, Abdelrahman-Sedky approved these changes
LGTM

2023-02-18 19:21 UTC, Abdelwahab-IO approved these changes

2023-02-18 19:21 UTC, merged